# Model internals
model:
  temperature: 0.5

# Retriever settings
retriever:
  retrieval_method: "bm25"
  k: 5

# Splitter settings (chunking)
splitter:
  chunk_size: 10
  chunk_overlap: 3
  max_message_length: 200